# Generated by fusen: do not edit by hand

library(dplyr)
test_that("bmi works", {
  
  test_that("1. not numeric", {
    expect_error(bmi(mass = 'toto', height = 1.80))
  })

  test_that("2. NA ok", {
    expect_equal(bmi(mass = NA, height = 1.80),NA)
  })

})
